<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * Contao
 * German translation file
 *
 * copyright  Tim Gatzky 2012
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['setTargetColName'] = array('Set target column','Choose here to select the target column.');
$GLOBALS['TL_LANG']['tl_form_field']['targetColName'] = array('Target column','Please choose the column to store the value in. If fields share the same target column the values will be combined. You can change this behaviour and the the seperator character in the config.php');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['form_db_field_legend'] = 'Store formdata settings';

?>