<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * Contao
 * German translation file
 *
 * copyright  Tim Gatzky 2012
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_form_field']['setTargetColName'] = array('Ziel-Spalte auswählen','Wählen Sie hier, wenn Sie die Zielspalte festlegen wollen.');
$GLOBALS['TL_LANG']['tl_form_field']['targetColName'] = array('Ziel-Spalte','Wählen Sie die Spalte in der Zieltabelle, in die die Daten gespeichert werden sollen. Teilen sich mehrere Formularfelder eine Spalte, werden die Werte ergänzt. Sie können dieses Verhalten mit Hilfe der Variablen in der config.php einstellen.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_form_field']['form_db_field_legend'] = 'Formulardaten speichern';

?>